---
- name: Config Eth
  hosts: inetRouter
  become: true
  tasks:
    - name: Install iptables
      package:
        name:
          - iptables
          - iptables-services
        state: latest
    - name: enable iptables
      service:
        name: iptables
        state: started
        enabled: yes
    - name: Flush iptables
      iptables:
        flush: yes
    - name: enable SNAT via iptables
      iptables:
        table: nat
        chain: POSTROUTING
        jump: SNAT
        out_interface: eth0
        to_source: 10.0.2.15
    - name: add knocking port
      become: yes
      shell: iptables-restore < /vagrant/confs/iptables.rules
    - name: ip forward    
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
    - name: add static route 
      copy:
        src: /vagrant/confs/route-eth1-inetrout
        dest: /etc/sysconfig/network-scripts/route-eth1
        owner: vagrant
        group: vagrant
      notify:
        - restart network service    
    - name: Ensure network is running
      service:
        name: network
        state: started
  handlers:
    - name: restart network service
      service:
        name: network
        state: restarted
    